project_id = "wxvsteaayxgygihpshoz"

[functions.sitemap]
verify_jwt = false

[functions.fetch-team-stats]
verify_jwt = false

[functions.update-team-stats-scheduled]
verify_jwt = false

[functions.send-subscription-confirmation]
verify_jwt = false

[functions.fetch-leagues]
verify_jwt = false

[functions.fetch-league-teams]
verify_jwt = false

[functions.fetch-league-matches]
verify_jwt = false

[functions.fetch-league-scores]
verify_jwt = false

[functions.fetch-team-logo]
verify_jwt = false

[functions.fetch-finished-matches]
verify_jwt = false

[functions.fetch-football-data]
verify_jwt = false

[functions.fetch-football-competitions]
verify_jwt = false

[functions.fetch-league-detail]
verify_jwt = false
