project_id = "wxvsteaayxgygihpshoz"

[functions.sitemap]
verify_jwt = false

[functions.fetch-team-stats]
verify_jwt = false

[functions.update-team-stats-scheduled]
verify_jwt = false

[functions.send-subscription-confirmation]
verify_jwt = false
